<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I2L0ULI" failures="1" tests="4" name="Test" time="24.135" errors="0" timestamp="2024-01-25T13:50:19 IST">
  <testcase classname="firstclass.TestTwo" name="testTwo" time="8.134"/>
  <testcase classname="firstclass.TestThree" name="testThree" time="6.319"/>
  <testcase classname="firstclass.LoginTest" name="login" time="1.787"/>
  <testcase classname="firstclass.LoginTest" name="login" time="1.189">
    <failure type="java.lang.AssertionError" message="expected [Failure] but found [Success]">
      <![CDATA[java.lang.AssertionError: expected [Failure] but found [Success]
at firstclass.LoginTest.login(LoginTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
